In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.9.0'

### 核，输入

In [3]:
kernel = np.arange(1, 10).reshape((3, 3))

In [4]:
kernel

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
C = np.array([[1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9, 0, 0, 0, 0, 0],
              [0, 1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9, 0, 0, 0, 0],
              [0, 0, 0, 0, 1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9, 0],
              [0,  0, 0, 0, 0, 1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9]])

In [6]:
input_ = np.arange(1, 17).reshape((4, 4))

In [7]:
input_

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### 卷积 in Numpy

In [8]:
x = input_.reshape((-1, 1))

In [9]:
x

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [10]:
y = C.dot(x)

In [11]:
y

array([[348],
       [393],
       [528],
       [573]])

In [12]:
y = y.reshape((2, 2))

In [13]:
y

array([[348, 393],
       [528, 573]])

### 卷积 in TensorFlow

In [14]:
x = tf.expand_dims(tf.expand_dims(tf.constant(input_, dtype=tf.float32), axis=-1), axis=0)

In [15]:
x.get_shape().as_list()

[1, 4, 4, 1]

In [16]:
kernel_conv = tf.expand_dims(tf.expand_dims(tf.constant(kernel, dtype=tf.float32), axis=-1), axis=-1)

In [17]:
kernel_conv.get_shape().as_list()

[3, 3, 1, 1]

In [18]:
y = tf.nn.conv2d(x, kernel_conv, strides=(1, 1, 1, 1), padding='VALID')

In [19]:
with tf.Session() as sess:
    print(y.eval()[0, :, :, 0])

[[348. 393.]
 [528. 573.]]
