In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.9.0'

### 核，输入

In [3]:
kernel = np.arange(1, 10).reshape((3, 3))

In [4]:
kernel

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
C = np.array([[1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9, 0, 0, 0, 0, 0],
              [0, 1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9, 0, 0, 0, 0],
              [0, 0, 0, 0, 1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9, 0],
              [0,  0, 0, 0, 0, 1, 2, 3, 0, 4, 5, 6, 0, 7, 8, 9]])

In [6]:
C_T = C.T

In [7]:
C_T

array([[1, 0, 0, 0],
       [2, 1, 0, 0],
       [3, 2, 0, 0],
       [0, 3, 0, 0],
       [4, 0, 1, 0],
       [5, 4, 2, 1],
       [6, 5, 3, 2],
       [0, 6, 0, 3],
       [7, 0, 4, 0],
       [8, 7, 5, 4],
       [9, 8, 6, 5],
       [0, 9, 0, 6],
       [0, 0, 7, 0],
       [0, 0, 8, 7],
       [0, 0, 9, 8],
       [0, 0, 0, 9]])

In [8]:
input_ = np.arange(1, 5).reshape((2, 2))

In [9]:
input_

array([[1, 2],
       [3, 4]])

### 转置卷积 in Numpy

In [10]:
x = input_.reshape((-1, 1))

In [11]:
x

array([[1],
       [2],
       [3],
       [4]])

In [12]:
y = C_T.dot(x)

In [13]:
y

array([[ 1],
       [ 4],
       [ 7],
       [ 6],
       [ 7],
       [23],
       [33],
       [24],
       [19],
       [53],
       [63],
       [42],
       [21],
       [52],
       [59],
       [36]])

In [14]:
y.reshape(4, 4)

array([[ 1,  4,  7,  6],
       [ 7, 23, 33, 24],
       [19, 53, 63, 42],
       [21, 52, 59, 36]])

### 转置卷积 in TensorFlow

In [15]:
x =  tf.expand_dims(tf.expand_dims(tf.constant(input_, dtype=tf.float32), axis=-1), axis=0)

In [16]:
x.get_shape().as_list()

[1, 2, 2, 1]

In [17]:
kernel_transpose_conv = tf.expand_dims(tf.expand_dims(tf.constant(kernel, dtype=tf.float32), axis=-1), axis=-1)

In [18]:
kernel_transpose_conv.get_shape().as_list()

[3, 3, 1, 1]

In [19]:
y = tf.nn.conv2d_transpose(x, kernel_transpose_conv, output_shape=(1, 4, 4, 1), strides=(1, 1, 1, 1), padding='VALID')

In [20]:
with tf.Session() as sess:
    print(y.eval()[0, :, :, 0])

[[ 1.  4.  7.  6.]
 [ 7. 23. 33. 24.]
 [19. 53. 63. 42.]
 [21. 52. 59. 36.]]
